---
proxy_secret_name: "migration-proxy"
http_proxy: "{{ lookup( 'env', 'HTTP_PROXY') }}"
https_proxy: "{{ lookup( 'env', 'HTTPS_PROXY') }}"
no_proxy: "{{ lookup( 'env', 'NO_PROXY') }}"
image_pull_policy: Always
cluster_subdomain: ""
rsync_transfer_image: "{{ registry }}/{{ project }}/{{ rsync_transfer_repo }}"
rsync_transfer_repo: "{{ lookup( 'env', 'RSYNC_TRANSFER_REPO') }}"
rsync_transfer_version: "{{ snapshot_tag | default(lookup( 'env', 'RSYNC_TRANSFER_TAG')) }}"
rsync_transfer_image_fqin: "{{ rsync_transfer_image }}:{{ rsync_transfer_version }}"
mig_operator_version: "1.7.7"
mig_namespace: "{{ lookup( 'env', 'WATCH_NAMESPACE') | default('openshift-migration') }}"
log_reader_state: absent
mig_log_reader_repo: "{{ lookup( 'env', 'MIG_LOG_READER_REPO') }}"
mig_log_reader_image: "{{ registry }}/{{ project }}/{{ mig_log_reader_repo }}"
mig_log_reader_version: "{{ snapshot_tag | default(lookup( 'env', 'MIG_LOG_READER_TAG')) }}"
mig_log_reader_image_fqin: "{{ mig_log_reader_image }}:{{ mig_log_reader_version }}"
migration_log_reader: true
migration_registry_image: "{{ registry }}/{{ project }}/{{ migration_registry_repo }}"
migration_registry_repo: "{{ lookup( 'env', 'MIGRATION_REGISTRY_REPO') }}"
migration_registry_version: "{{ lookup( 'env', 'MIGRATION_REGISTRY_TAG') }}"
migration_registry_image_fqin: "{{ migration_registry_image }}:{{ migration_registry_version }}"
migration_stage_image: "{{ registry }}/{{ project }}/{{ velero_restic_restore_helper_repo }}"
migration_stage_repo: "{{ lookup( 'env', 'VELERO_RESTIC_RESTORE_HELPER_REPO') }}"
migration_stage_version: "{{ snapshot_tag | default(lookup( 'env', 'VELERO_RESTIC_RESTORE_HELPER_TAG')) }}"
migration_stage_image_fqin: "{{ migration_stage_image }}:{{ migration_stage_version }}"
migration_rsync_privileged: false
enable_intelligent_pv_resize: true
registry: "{{ lookup( 'env', 'REGISTRY') }}"
project: "{{ lookup( 'env', 'PROJECT') }}"
restic_pv_host_path: /var/lib/kubelet/pods
restic_timeout: 1h
restic_supplemental_groups: []
velero_aws_secret_name: cloud-credentials
velero_gcp_secret_name: cloud-credentials-gcp
velero_azure_secret_name: cloud-credentials-azure
velero_debug: false
velero_image: "{{ registry }}/{{ project }}/{{ velero_repo }}"
velero_repo: "{{ lookup( 'env', 'VELERO_REPO') }}"
velero_version: "{{ snapshot_tag | default(lookup( 'env', 'VELERO_TAG')) }}"
velero_image_fqin: "{{ velero_image }}:{{ velero_version }}"
velero_plugin_image: "{{ registry }}/{{ project }}/{{ velero_plugin_repo }}"
velero_plugin_repo: "{{ lookup( 'env', 'VELERO_PLUGIN_REPO') }}"
velero_plugin_version: "{{ snapshot_tag | default(lookup( 'env', 'VELERO_PLUGIN_TAG')) }}"
velero_plugin_fqin: "{{ velero_plugin_image }}:{{ velero_plugin_version }}"
velero_restic_restore_helper_image: "{{ registry }}/{{ project }}/{{ velero_restic_restore_helper_repo }}"
velero_restic_restore_helper_repo: "{{ lookup( 'env', 'VELERO_RESTIC_RESTORE_HELPER_REPO') }}"
velero_restic_restore_helper_version: "{{ snapshot_tag | default(lookup( 'env', 'VELERO_RESTIC_RESTORE_HELPER_TAG')) }}"
velero_restic_restore_helper_fqin: "{{ velero_restic_restore_helper_image }}:{{ velero_restic_restore_helper_version }}"
velero_aws_plugin_image: "{{ registry }}/{{ project }}/{{ velero_aws_plugin_repo }}"
velero_aws_plugin_repo: "{{ lookup( 'env', 'VELERO_AWS_PLUGIN_REPO') }}"
velero_aws_plugin_version: "{{ snapshot_tag | default(lookup( 'env', 'VELERO_AWS_PLUGIN_TAG')) }}"
velero_aws_plugin_fqin: "{{ velero_aws_plugin_image }}:{{ velero_aws_plugin_version }}"
velero_gcp_plugin_image: "{{ registry }}/{{ project }}/{{ velero_gcp_plugin_repo }}"
velero_gcp_plugin_repo: "{{ lookup( 'env', 'VELERO_GCP_PLUGIN_REPO') }}"
velero_gcp_plugin_version: "{{ snapshot_tag | default(lookup( 'env', 'VELERO_GCP_PLUGIN_TAG')) }}"
velero_gcp_plugin_fqin: "{{ velero_gcp_plugin_image }}:{{ velero_gcp_plugin_version }}"
velero_azure_plugin_image: "{{ registry }}/{{ project }}/{{ velero_azure_plugin_repo }}"
velero_azure_plugin_repo: "{{ lookup( 'env', 'VELERO_AZURE_PLUGIN_REPO') }}"
velero_azure_plugin_version: "{{ snapshot_tag | default(lookup( 'env', 'VELERO_AZURE_PLUGIN_TAG')) }}"
velero_azure_plugin_fqin: "{{ velero_azure_plugin_image }}:{{ velero_azure_plugin_version }}"
velero_state: absent
velero_qps: 100
velero_burst: 1000
